version: '3.8'

services:
  database-nestjs:
    container_name: database-nestjs
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database
